service:
  version: 1.1.1
  url: http://fbinter.stadt-berlin.de/fb/wms/senstadt/berlinzoom
  srs: EPSG:3068
  format: jpeg
  layer: 0
bbox:
  west:  23600.0
  south: 20900.0
  east:  48000.0
  north: 39000.0

size: 1000
resolution: 1000
timeout: 300
projection: EPSG:3068
directory: images
vrtfile: tiles.vrt
tmpfile: /tmp/wms.xml
