service:
  version: 1.1.1
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild1953?
  srs: EPSG:25833
  format: png
  layer: 0
  transparent: True

bbox:
  west:   370000.0
  south: 5800000.0
  east:   415000.0
  north: 5837000.0

size: 1000
resolution: 2000
timeout: 500
projection: EPSG:25833
directory: png
vrtfile: tiles.vrt
tmpfile: /tmp/wms.xml
bandscount: 1
